import type PageController from "sap/fe/core/PageController";
import type { ValueState } from "sap/ui/core/library";
export type PssResults = {
    Material: string;
    _PssParams: PssParams;
    _PssReplacements: SuperSessionReplacementParts[];
};
type DialogMode = "A" | "N" | "S";
type SelectionMode = "S" | "M";
export type SuperSessionReplacementParts = {
    PartType: PartType;
    PartUid: string;
    BundlendlUid: string;
    ReplacmentItemType: ReplacementItemType;
    ReplacmentLevel: number;
    Material: string;
    MaterialDescription: string;
    DateFrom: string;
    UnrestrictedStockQty: string;
    AvailableQty: string;
    TargetQty: string;
    QtyUom: string;
    ReplacementType: ReplacementType;
    PicCode: string;
    Material18: string;
    OemNumber: string;
    ManufacturerPartNumber: string;
    PartQuantity: string;
    Mark: boolean;
    UsedPart: boolean;
    ExMatm: boolean;
    ExOrim: boolean;
};
export type OrderItemParam = {
    ItemCategory: string;
    ItemCategoryDescription: string;
    TechItemCategory: string;
    ItemObjectID: string;
    Description1: string;
    Quantity: string;
    QuantityUOM: string;
};
export type OrderItem = {
    OrderID: string;
    Item: string;
    MaterialShort: string;
    MaterialLong: string;
    LaborValue: string;
    OEM: string;
    Batch: string;
    MaterialGroup: string;
    ShortText: string;
    Description1: string;
    Description2: string;
    Description3: string;
    Description4: string;
    ItemCategory: string;
    TechItemCategory: string;
    ItemDelete: boolean;
    ItemType: string;
    Quantity: number;
    QuantityUOM: string;
    BillingBlock: string;
    ReplacementPart: string;
    Division: string;
    NettoValue: number;
    Currency: string;
    PartialDelivery: string;
    SalesUoM: string;
    GrossWeight: number;
    NettoWeight: number;
    WeightUoM: string;
    Volume: number;
    VolumeUoM: string;
    Plant: string;
    StorageLocation: string;
    CreatedAt: string;
    CreatedBy: string;
    CreatedTimeAt: string;
    NettoPrice: number;
    ReturnsItem: boolean;
    CashDiscount: boolean;
    MaterialPriceGroup: string;
    AccountAssignmentGroupMaterial: string;
    VolumeRebateGroup: string;
    CommissionGroup: string;
    CustomerGroup: string;
    ProfitCenter: string;
    Job: string;
    Split: string;
    OrderType: string;
    ProductHierarchy: string;
    PurchasePrice: number;
    DeliveryDate: string;
    ReturnPart: string;
    SalesPrice: number;
    StatusPartsToBeReturned: string;
    StorageBin: string;
    InvalidMaterialforMRP: boolean;
    ItemObjectID: string;
    RejectionReason: string;
    MaterialGroup1: string;
    StatusProcedure: string;
    ProcessStatus: string;
    ShippingPointReceivingPoint: string;
    ATPStatus: string;
    ATPStatusCriticality: number;
    AlterQuantity: number;
    HeaderPriceConditionNo: string;
    DiscountPart: number;
    DiscountPartUoM: string;
    SurchargePart: number;
    SurchargePartUoM: string;
    FixedPricePart: number;
    FixedPricePartCurrency: string;
    isTextItem: boolean;
    ProcessStatusIcon: string;
    ItemCategoryDescription: string;
    ProcessStatusDescription: string;
};
export type ExtendedSuperSessionReplacementParts = {
    partStatus: ValueState;
    icon: string;
    isStandalonePart: boolean;
    isVisible: boolean;
} & SuperSessionReplacementParts;
export type ItemMaterial = {
    orderId: string;
    itemCategory: string;
    techItemCategory: string;
    material: string;
    description: string;
    qty: string;
    uom: string;
};
export type MessageParam = {
    showErrorMessage: boolean;
};
export type DialogModel = {
    mainPart: ItemMaterial;
    pssReplacementparts: ExtendedSuperSessionReplacementParts[];
    pssparams: PssParams;
    messageParam: MessageParam;
};
export type PssParams = {
    DialogMode: DialogMode;
    SelectionMode: SelectionMode;
    KeyDateMode: string;
};
export type OrderItemContext = {
    contextPath: string;
    createParameters: Record<OrderItemKeys, string>[];
};
export type OrderItemKeys = "ItemCategory" | "ItemCategoryDescription" | "TechItemCategory" | "ItemObjectID" | "Description1" | "QuantityUOM" | "Quantity";
type PartType = "P" | "B";
export type ReplacementItemType = "A" | "B" | "C";
export type ReplacementType = "F" | "I" | "N" | "O";
export type ObjectPageBaseController = {
    base: PageController;
};
export {};
