import Controller from "sap/ui/core/mvc/Controller";
/**
 * @namespace vss.com.pblg.controller
 */
export default class Main extends Controller {
    onInit(): void;
    private onVSSOrderValueHelpOpened;
    private onDivisionValueHelpOpened;
    private onPurchaseOrderValueHelpOpened;
    private onMaterialPlantValueHelpOpened;
    onBeforeRendering(): void;
    private onButtonCentralizedSalesOrgPress;
    private setCustomFilters;
    private getObjIdentifier;
    private registerForP13n;
    private getKeyForItem;
    private onTableSort;
    private onTableColumnMove;
    private onVariantManagementChange;
    private onVariantManagementSave;
    private onTableCellClick;
    private onTableColumnResize;
    private onHandleStateChange;
    private handleStateChange;
    private getColumnKey;
    onAfterRendering(): void | undefined;
    private updateFilterItemsState;
    private onSelectionCriteriaSelectChange;
    private getDialog;
    private setupDefaultModel;
    private onButtonMessagePopoverPress;
    private bindTableModel;
    private factoryColumnTemplate;
    private onFilterBarVisibilityButtonPress;
    private onStorageLocationSelectChange;
    private determineControlFromColumn;
    private updateAssignedQuantityStatuses;
    private onQuantityInputChange;
    private onButtonPress;
    private preprocessSubmitSequenceKeys;
    private getBaseConditionForSubmitSinglePO;
    private getAdditionalConditionForSubmitSinglePO;
    private fireSubmitGeneric;
    private constructSubmitGenericPrecheck;
    private constructSubmitGeneric;
    private constructSubmitSelected;
    private constructSubmitAll;
    private getTable;
    private getStorageLocations;
    private getFilterBar;
    private getMessagePopoverBtn;
    private getMessagePopoverBtnData;
    private getMessagesModel;
    private getDefaultModel;
    private onFilterBarSearch;
    private onCustomButtonOrgDataPress;
    private onButtonOrgDataEndPress;
    private onFiltersChanged;
    private constructSubmitEntity;
    private onButtonGenericPress;
    private onButtonSubmitAllPress;
    private onButtonSubmitSelectedPress;
    private onBarcodeScannerButtonScanSuccess;
    private onBarcodeScannerButtonInputLiveUpdate;
    private onTrackingNumberChange;
    private setControlsBusy;
    private unsetControlsBusy;
    private onButtonTableP13nPress;
    private newInitialRequest;
    private onTableScrollingGenericPress;
    private onPreviousPageButtonPress;
    private onButtonSingleUpPress;
    private onButtonSingleDownPress;
    private onNextPageButtonPress;
}
