import type { Select$ChangeEvent } from "sap/m/Select";
import type Event from "sap/ui/base/Event";
import Controller from "sap/ui/core/mvc/Controller";
import type { StateP13n } from "vss/com/pblg/library/Types";
/**
 * @namespace vss.com.pblg.controller
 */
export default class Main extends Controller {
    onInit(): void;
    onVSSOrderValueHelpOpened(oEvent: Event): void;
    onDivisionValueHelpOpened(oEvent: Event): void;
    onPurchaseOrderValueHelpOpened(oEvent: Event): void;
    onMaterialPlantValueHelpOpened(oEvent: Event): void;
    onBeforeRendering(): void;
    onButtonCentralizedSalesOrgPress(): void;
    private setCustomFilters;
    private getObjIdentifier;
    private registerForP13n;
    private getKeyForItem;
    onTableSort(oEvent: Event): void;
    onTableColumnMove(oEvent: Event): void;
    onVariantManagementChange(): void;
    onVariantManagementSave(): void;
    onTableCellClick(oEvent: Event): void;
    onTableColumnResize(oEvent: Event): void;
    onHandleStateChange(oState: StateP13n): void;
    private handleStateChange;
    private getColumnKey;
    onAfterRendering(): void | undefined;
    private updateFilterItemsState;
    onSelectionCriteriaSelectChange(oEvent: Event): void;
    private getDialog;
    private setupDefaultModel;
    onButtonMessagePopoverPress(oEvent: Event): void;
    private bindTableModel;
    private factoryColumnTemplate;
    onFilterBarVisibilityButtonPress(oEvent: Event): void;
    onStorageLocationSelectChange(oEvent: Select$ChangeEvent): void;
    private determineControlFromColumn;
    private updateAssignedQuantityStatuses;
    onQuantityInputChange(oEvent: Event): void;
    onButtonPress(oEvent: Event): void;
    private preprocessSubmitSequenceKeys;
    private getBaseConditionForSubmitSinglePO;
    private getAdditionalConditionForSubmitSinglePO;
    private fireSubmitGeneric;
    private constructSubmitGenericPrecheck;
    private constructSubmitGeneric;
    private constructSubmitSelected;
    private constructSubmitAll;
    private getTable;
    private getStorageLocations;
    private getFilterBar;
    private getMessagePopoverBtn;
    private getMessagePopoverBtnData;
    private getMessagesModel;
    private getDefaultModel;
    onFilterBarSearch(): void;
    onCustomButtonOrgDataPress(): void;
    onButtonOrgDataEndPress(): void;
    onFiltersChanged(oEvent: Event): void;
    private constructSubmitEntity;
    onButtonGenericPress(sTitle: string, iMode: int, oEvent?: Event): void;
    onButtonSubmitAllPress(oEvent: Event): void;
    onButtonSubmitSelectedPress(oEvent: Event): void;
    onBarcodeScannerButtonScanSuccess(oEvent: Event): void;
    onBarcodeScannerButtonInputLiveUpdate(oEvent: Event): void;
    onTrackingNumberChange(sTrackingNumber: string, bOverride: boolean): void;
    private setControlsBusy;
    private unsetControlsBusy;
    onButtonTableP13nPress(oEvent: Event): void;
    private newInitialRequest;
    onTableScrollingGenericPress(oEvent: Event, iDiff: int): void;
    onPreviousPageButtonPress(oEvent: Event): void;
    onButtonSingleUpPress(oEvent: Event): void;
    onButtonSingleDownPress(oEvent: Event): void;
    onNextPageButtonPress(oEvent: Event): void;
}
