import { ValueState } from "sap/ui/core/library";
import type { HiddableTextObject, OrderIdentifier, POIdentifier, ProductDescription, StorageLocationSelect, TableAllData } from "vss/com/pblg/library/Types";
import type { POIdentifierOData } from "vss/com/pblg/library/TypesOData";
export declare function notInitial(x: string | number | undefined): boolean;
export declare function isCorrespondingPOAvailable(aTableData: POIdentifierOData[], sPODelivery: string | undefined, sPOPositionNumber: string | undefined): boolean;
export declare function isPOEqual(oPO_1: POIdentifier, oPO_2: POIdentifier): boolean;
export declare function isVSSOrderKeyIdentical(oVSSOrder1: OrderIdentifier, oVSSOrder2: OrderIdentifier): boolean;
export declare function isStock(sText: string): boolean;
export declare function orderTextFormatter(sText: string): boolean;
export declare function defaultTextFormatter(sText: string): boolean;
export declare function POTextFormatter(sText: HiddableTextObject | undefined): boolean;
export declare function normalTextFormatter(sText: string): string;
export declare function hiddableTextFormatter(sText: HiddableTextObject): string;
export declare function defaultTooltipFormatter(sText: HiddableTextObject | undefined): string;
export declare function isStorageLocationFound(location: string[] | string): boolean;
export declare function storageLocationTextFormatter(sText: string): boolean;
export declare function storageLocationSelectFormatter(sText: string): boolean;
export declare function storageLocationSelectedKeyFormatter(aLocations: StorageLocationSelect[]): string;
export declare function priorityTextFormatter(x: TableAllData["Priority"]): string;
export declare function priorityValueStateFormatter(x: TableAllData["Priority"]): ValueState;
export declare function getHiddableTextObject(sRealValue: int | string | HiddableTextObject, sDisplayValue?: int | string): HiddableTextObject;
export declare function assignedQuantityFormatter(oQuantity: TableAllData["AssignedQuantity"]): string;
export declare function assignedQuantityTextFormatter(oQuantity: TableAllData["AssignedQuantity"]): string;
export declare function assignedQuantityValueStateFormatter(oQuantity: TableAllData["AssignedQuantity"]): ValueState.Error | ValueState.None;
export declare function getProductDescription(x: ProductDescription[], y: ProductDescription): string;
