import type Button from "sap/m/Button";
import { ButtonType } from "sap/m/library";
import type Message from "sap/ui/core/message/Message";
import MessageType from "sap/ui/core/message/MessageType";
import type JSONModel from "sap/ui/model/json/JSONModel";
import type { BackendMessage, SubmitEntity } from "vss/com/pblg/library/Types";
export declare const sSeqKeyBackendMessageCode = "/DBE/DAPB/000";
export declare function setMessagesModel(x: JSONModel): void;
export declare function getMessagesModel(): JSONModel;
export declare function initMessagePopover(oMessagePopoverBtn: Button): void;
export declare function setMessageType(sType: BackendMessage["type"]): MessageType;
export declare function buttonIconFormatter(aMessages: Message[]): string;
export declare function buttonTypeFormatter(aMessages: Message[]): ButtonType;
export declare function highestSeverityMessages(sHighestSeverityIconType: ButtonType, aMessages: Message[]): int;
export declare function setGroupName(oItem: SubmitEntity | undefined): string;
export declare function formatMessageButton(oMessagePopoverBtn: Button, aMessages: Message[]): void;
export declare function clearMessages(oMessagePopoverBtn: Button): void;
export declare function processSubmitResults(oMessagePopoverBtn: Button, aMessages: Message[]): void;
