import type Select from "sap/m/Select";
import type FilterBar from "sap/ui/mdc/FilterBar";
import type FilterField from "sap/ui/mdc/FilterField";
import type { ConditionObject } from "sap/ui/mdc/condition/Condition";
import type FilterBarVH from "sap/ui/mdc/filterbar/vh/FilterBar";
import Filter from "sap/ui/model/Filter";
import type OData4Model from "sap/ui/model/odata/v4/ODataModel";
import type { POReadExtendedIdentifier } from "vss/com/pblg/library/Types";
export declare function getFiltersFromFilterBar(oFilterBar: FilterBar): Filter[];
export declare function getFilterFieldByPropertyKey(oFilterBar: FilterBar | FilterBarVH, sPropertyKey: string): FilterField | undefined;
export declare function getFiltersFromConditions(oConditions: Record<string, ConditionObject[]>): Filter[];
export declare function getFilterBarConditions(oFilterBar: FilterBar): Record<string, any>;
export declare function conditionExists(oFilterBar: FilterBar, sCondition: string): boolean;
export declare function initSelectionCriteriaSelect(oFilterBar: FilterBar, oModel: OData4Model, oSelectionCriteriaSelect: Select): Select;
export declare function mergeAllFilters(oFilterBar: FilterBar, aMoreOrders: POReadExtendedIdentifier[]): Filter[];
export declare function getCustomFilters(oFilterBar: FilterBar | FilterBarVH): void;
