import CustomData from "sap/ui/core/CustomData";
import type Message from "sap/ui/core/message/Message";
import type Table from "sap/ui/table/Table";
import type { StorageLocations } from "vss/com/pblg/library/Types";
export declare const _cd_consts: {
    sCDTableFiltered: string;
    sCDPONumber: string;
    sCDMessages: string;
    sCDStorages: string;
};
export declare function rememberCustomData(oTable: Table): Table;
export declare function storeMessagesCustomData(oTable: Table): Table;
export declare function storeStoragesCustomData(oCustomData: CustomData, aStorages: any[]): void;
export declare function getStoragesCustomData(oCustomData: CustomData, sPlant?: StorageLocations["Plant"]): StorageLocations[];
export declare function setMessagesCustomData(oTable: Table, aMessages: Message[]): Table;
export declare function getMessagesCustomData(oTable: Table): Message[];
export declare function rememberIfTableFiltered(oTable: Table): Table;
export declare function rememberPONumber(oTable: Table): Table;
export declare function setPONumber(oTable: Table, iValue: int): Table;
export declare function getPONumber(oTable: Table): int;
export declare function setTableFiltered(oTable: Table, bValue: boolean): Table;
export declare function getTableFiltered(oTable: Table): boolean;
