import Filter from "sap/ui/model/Filter";
import OData4ListBinding from "sap/ui/model/odata/v4/ODataListBinding";
import OData4Context from "sap/ui/model/odata/v4/Context";
import OData4Model from "sap/ui/model/odata/v4/ODataModel";
import Table from "sap/ui/table/Table";
import Event from "sap/ui/base/Event";
import { SubmitEntityOData, TableAllDataOData } from "../library/TypesOData";
export declare const _entity_paths: {
    sPurchasingDocuments: string;
    sOrders: string;
    sOrdersSubmit: string;
    sStorageLocations: string;
    sSelectionCriteria: string;
};
export declare function limitInitialPORequest(oModel: OData4Model): void;
export declare function limitInitialVSSRequest(oModel: OData4Model): void;
export declare function limitRequest(iCounter: int, oModel: OData4Model): void;
export declare function isMoreOrdersAvailable(iCounter: int, iDefaultThreshold?: int): boolean;
export declare function getNewGrowingThresholdForPO(iCounter: int): int;
export declare function getNoOrdersToBeRequested(iCounter: int): int;
export declare function getOrdersGrowingThreshold(): int;
export declare function getPOGrowingThreshold(): int;
export declare function getDefaultTableThreshold(): int;
export declare function requestOrders(oModel: OData4Model, aFilters?: Array<Filter>): OData4ListBinding;
export declare function requestStorageLocations(oModel: OData4Model): OData4ListBinding;
export declare function requestSelectionCriteria(oModel: OData4Model): OData4ListBinding;
export declare function requestSelectionCriteriaUpdate(oModel: OData4Model, sSelCri: string): void;
export declare function logCreateCompleted(oEvent: Event): void;
export declare function requestOrdersSubmit(oModel: OData4Model, aObj: Array<SubmitEntityOData | undefined>, oTable: Table): void;
export declare function getODataObjectsFromResults(aResults: Array<OData4Context>): Array<TableAllDataOData>;
