import Filter from "sap/ui/model/Filter";
import type { POIdentifier, SubmitEntity, TableColumns } from "vss/com/pblg/library/Types";
import type { SubmitEntityOData, TableColumnsOData } from "vss/com/pblg/library/TypesOData";
export declare function getSubmitSequenceKey(data: SubmitEntityOData): string;
export declare function getSequenceKey(rowData: POIdentifier, iCounter?: int): string;
export declare function getSubmitSequenceKeyFilter(sSubmitSequenceKey: string): Filter;
export declare function getSequenceKeyFilter(sSequenceKey: string, bSingular: boolean): Filter;
export declare function getFiltersForOrdersSubmitRequest(aSequenceKeys: string[]): Filter[];
export declare function getFiltersForOrdersRequest(aSequenceKeys: string[]): Filter[];
export declare function getInitialSequenceKeys(aRowData: TableColumns[]): string[];
export declare function getSubmitSequenceKeys(aRowData: TableColumnsOData[]): string[];
export declare function getUniqueArray(aArr: unknown[]): unknown[];
export declare function parseSequenceKey(sSequenceKey: string): SubmitEntity | undefined;
export declare function getSubmitKeys(aRowData: TableColumnsOData[]): SubmitEntityOData[];
export declare function parseSequenceKeys(aFilters: Filter[]): (SubmitEntity | undefined)[];
export declare function getStorageLocation(x: TableColumnsOData | TableColumns): string;
