import Table from "sap/m/Table";
import ObjectPageLayout from "sap/uxap/ObjectPageLayout";
import Event from "sap/ui/base/Event";
import { MaterialOverview } from "vss/com/dapv/entities/Entities";
export declare function getStockOverviewTableItems(oTable: Table, aStockOverview: MaterialOverview["_StockOverview"]): void;
export declare function constructStockSection(oObjPageLayout: ObjectPageLayout, aStockOverview: MaterialOverview["_StockOverview"]): void;
export declare function getStockOverviewTable(aStockOverview: MaterialOverview["_StockOverview"]): Table;
export declare function onStockPreviewAll(oEvent: Event): void;
export declare function onStockPreviewReduce(oEvent: Event): void;
export declare function getStockOverviewTableColumns(oTable: Table): void;
export declare function setStockOverview(aStockOverview: MaterialOverview["_StockOverview"]): void;
export declare function setStockTable(oTable: Table): void;
