import Table from "sap/m/Table";
import type Event from "sap/ui/base/Event";
import type ObjectPageLayout from "sap/uxap/ObjectPageLayout";
import type { ItemsInfo, JobItems, JobOverview, MainTable, OrderPositionOverview } from "vss/com/dapv/entities/Entities";
import type { OrderOverviewHeader } from "vss/com/dapv/utils/UtilsFrontendData";
export declare function getOrderOverviewHeader(x: MainTable): OrderOverviewHeader;
export declare function getOrderItemsTableColumns(oTable: Table): void;
export declare function getOrderItemsTableItems(oTable: Table, aOrderPosition: OrderPositionOverview[]): void;
export declare function onMaterialOverviewPress(oEvent: Event): void;
export declare function onButtonProcureSinglePress(oEvent: Event): void;
export declare function getOrderItemsTable(oJobOverview: JobOverview): Table;
export declare function getOrderPositionOverview(oOrderData: MainTable, oItemsInfo: ItemsInfo): OrderPositionOverview;
export declare function getJobWithOrderItems(oJob: JobItems, oOrderData: MainTable): JobOverview;
export declare function constructSections(aJobOverview: JobOverview[], oObjPageLayout: ObjectPageLayout): void;
