import type Button from "sap/m/Button";
import MessagePopover from "sap/m/MessagePopover";
import { ButtonType } from "sap/m/library";
import type Event from "sap/ui/base/Event";
import type Message from "sap/ui/core/message/Message";
import MessageType from "sap/ui/core/message/MessageType";
import type { BackendMessage } from "vss/com/dapv/entities/Entities";
export declare function initMessagePopover(oMessagePopoverBtn: Button): MessagePopover;
export declare function onButtonMessagePopoverPress(oEvent: Event): void;
export declare function setMessageType(sType: BackendMessage["type"]): MessageType;
export declare function buttonIconFormatter(aMessages: Message[]): string;
export declare function buttonTypeFormatter(aMessages: Message[]): ButtonType;
export declare function highestSeverityMessages(sHighestSeverityIconType: ButtonType, aMessages: Message[]): int;
export declare function setGroupName(sMessage: string): string;
export declare function setMessagePopoverMessages(oMessagePopover: MessagePopover, aMessages: Message[] | undefined): void;
export declare function processSubmitResults(oMessagePopoverBtn: Button, aMessages: Message[] | undefined, bDisplay: boolean, bWrite: boolean): void;
