import HBox from "sap/m/HBox";
import Input from "sap/m/Input";
import Control from "sap/ui/core/Control";
import CustomData from "sap/ui/core/CustomData";
export declare const sNegativeTextColor: string;
export declare const sCriticalTextColor: string;
export declare const sPositiveTextColor: string;
export declare const sNegativeBgColor: string;
export declare const sCriticalBgColor: string;
export declare const sPositiveBgColor: string;
export declare const sColorGreenBackground: string;
export declare const sColorYellowBackground: string;
export declare const sColorRedBackground: string;
export declare const oCustomDataIds: {
    sNewConfQuantity: string;
    sOriginalATPValue: string;
    sOrderNumber: string;
    sOrderPosition: string;
    sQuantityMeasure: string;
    sOrderQuantity: string;
    sDiffConfNewConf: string;
    sPostedQuantity: string;
};
export declare function setInputCustomColor(oInput: Input, sBackgroundColor: string, sForegroundColor: string): void;
export declare function getFioriColor(sFioriColor: string): string;
export declare function findChildrenWithClass(aChildNodes: HTMLElement[], sClass: string): HTMLElement[];
export declare function getControlCustomDataKey(oControl: Control, sKey: string): CustomData;
export declare function getControlCustomDataValue(oControl: Control, sKey: string): any;
export declare function getCustomDataValue(oCustomData: CustomData): any;
export declare function determineInputSetting(oHBox: HBox, fUpdateValue?: number): void;
