import HBox from "sap/m/HBox";
import Input from "sap/m/Input";
import Control from "sap/ui/core/Control";
import CustomData from "sap/ui/core/CustomData";
export declare let sNegativeTextColor: string;
export declare let sCriticalTextColor: string;
export declare let sPositiveTextColor: string;
export declare let sNegativeBgColor: string;
export declare let sCriticalBgColor: string;
export declare let sPositiveBgColor: string;
export declare let sColorGreenBackground: string;
export declare let sColorYellowBackground: string;
export declare let sColorRedBackground: string;
export declare const oCustomDataIds: {
    sNewConfQuantity: string;
    sOriginalATPValue: string;
    sOrderNumber: string;
    sOrderPosition: string;
    sQuantityMeasure: string;
    sOrderQuantity: string;
    sDiffConfNewConf: string;
    sPostedQuantity: string;
};
export declare function updateLaunchpadThemeSettings(oObj: any): void;
export declare function getFioriColor(sFioriColor: string): string;
export declare function getLaunchpadThemeSettings(sTheme: string): {
    sNegativeTextColor: string;
    sCriticalTextColor: string;
    sPositiveTextColor: string;
    sNegativeBgColor: string;
    sCriticalBgColor: string;
    sPositiveBgColor: string;
    sColorGreenBackground: string;
    sColorYellowBackground: string;
    sColorRedBackground: string;
};
export declare function setInputCustomColor(oInput: Input, sBackgroundColor: string, sForegroundColor: string): void;
export declare function findChildrenWithClass(aChildNodes: HTMLElement[], sClass: string): HTMLElement[];
export declare function getControlCustomDataKey(oControl: Control, sKey: string): CustomData;
export declare function getControlCustomDataValue(oControl: Control, sKey: string): any;
export declare function getCustomDataValue(oCustomData: CustomData): any;
export declare function determineInputSetting(oHBox: HBox, fUpdateValue?: number): void;
