import FilterBarVH from "sap/ui/mdc/filterbar/vh/FilterBar";
import FilterBar from "sap/ui/mdc/FilterBar";
import FilterField from "sap/ui/mdc/FilterField";
import Filter from "sap/ui/model/Filter";
export declare function getFiltersFromFilterBar(oFilterBar: FilterBar): Filter[];
export declare function getFilterFieldByPropertyKey(oFilterBar: FilterBar | FilterBarVH, sPropertyKey: string): FilterField | undefined;
export declare function getFiltersFromConditions(oConditions: Record<string, any>): Filter[];
export declare function getFilterBarConditions(oFilterBar: FilterBar): Record<string, any>;
export declare function conditionExists(oFilterBar: FilterBar, sCondition: string): boolean;
export declare function getCustomFilters(oFilterBar: FilterBar | FilterBarVH): void;
