import Table from "sap/m/Table";
import Button from "sap/m/Button";
import Input from "sap/m/Input";
import ObjectPageLayout from "sap/uxap/ObjectPageLayout";
import Event from "sap/ui/base/Event";
import OData4Model from "sap/ui/model/odata/v4/ODataModel";
import { MaterialOverview } from "vss/com/dapv/entities/Entities";
export declare function getATPOverviewTableItems(oTable: Table, aATPOverview: MaterialOverview["_OrderAtp"], bAvailabilityCheck: boolean): void;
export declare function onATPAvailabilityCheckSinglePress(oEvent: Event): void;
export declare function onATPAvailabilityCheckMultiplePress(oEvent: Event): void;
export declare function onActionGeneric(oModel: OData4Model, bAvailabilityCheck: boolean): void;
export declare function onATPAvailabilityCheckProcessing(oModel: OData4Model, oEvent: Event): void;
export declare function onATPCall(oEvent: Event): void;
export declare function onATPOverviewTableAfterRendering(): void;
export declare function toNumber(str: string): number;
export declare function setMemoATPDiff(): void;
export declare function onATPInputChange(oEvent: Event): void;
export declare function changeATPButtonValueBy(oInput: Input, iDiff: int): void;
export declare function getUpdateConfQuanButton(): Button;
export declare function getResetQuanButton(): Button;
export declare function constructATPSection(oObjPageLayout: ObjectPageLayout, aATPOverview: MaterialOverview["_OrderAtp"], bAvailabilityCheck: boolean): void;
export declare function onATPReset(): void;
export declare function onATPTaphold(oInput: Input, iDiff: int): void;
export declare function onATPButtonPress(oEvent: Event, iDiff: int): void;
export declare function getATPOverviewTableColumns(oTable: Table): void;
export declare function getATPOverviewTable(aATPOverview: MaterialOverview["_OrderAtp"], bAvailabilityCheck: boolean): Table;
export declare function setATPTable(oTable: Table): void;
export declare function setATPButton(oButton: Button): void;
export declare function getATPColumnStyleClass(sLocalId: string): string;
export declare function getATPColumnIndex(sLocalId: string): number;
export declare function onATPButtonLessPress(oEvent: Event): void;
export declare function onATPButtonAddPress(oEvent: Event): void;
export declare function onATPButtonLessTaphold(oInput: Input): void;
export declare function onATPButtonAddTaphold(oInput: Input): void;
export declare function removeTrailingZeros(sData: string): string;
export declare function parseOrderNoAndPos(sData: string): {
    orderNumber: string;
    orderPosition: string;
};
