import type HBox from "sap/m/HBox";
import type Input from "sap/m/Input";
import type Control from "sap/ui/core/Control";
import type CustomData from "sap/ui/core/CustomData";
import type { CustomFioriColorSettings } from "vss/com/dapv/utils/UtilsFrontendData";
export declare let sNegativeTextColor: string;
export declare let sCriticalTextColor: string;
export declare let sPositiveTextColor: string;
export declare let sNegativeBgColor: string;
export declare let sCriticalBgColor: string;
export declare let sPositiveBgColor: string;
export declare let sColorGreenBackground: string;
export declare let sColorYellowBackground: string;
export declare let sColorRedBackground: string;
export declare const oCustomDataIds: {
    sNewConfQuantity: string;
    sOriginalATPValue: string;
    sOrderNumber: string;
    sOrderPosition: string;
    sQuantityMeasure: string;
    sOrderQuantity: string;
    sDiffConfNewConf: string;
    sPostedQuantity: string;
};
export declare function updateLaunchpadThemeSettings(oObj: CustomFioriColorSettings): void;
export declare function getFioriColor(sFioriColor: string): string;
export declare function getLaunchpadThemeSettings(sTheme: string): CustomFioriColorSettings;
export declare function setInputCustomColor(oInput: Input, sBackgroundColor: string, sForegroundColor: string): void;
export declare function findChildrenWithClass(aChildNodes: HTMLElement[], sClass: string): HTMLElement[];
export declare function getControlCustomDataKey(oControl: Control, sKey: string): CustomData;
export declare function getControlCustomDataValue(oControl: Control, sKey: string): unknown;
export declare function getCustomDataValue(oCustomData: CustomData): unknown;
export declare function determineInputSetting(oHBox: HBox, fUpdateValue?: number): void;
