import type { IContentContainer, IItemsContainer } from "dbme/c/model/CommonType";
import type UI5Element from "sap/ui/core/Element";
import type Table from "sap/ui/table/Table";
import type ResponsiveTable from "sap/m/Table";
import type SmartTable from "sap/ui/comp/smarttable/SmartTable";
import type SmartFilterBar from "sap/ui/comp/smartfilterbar/SmartFilterBar";
import type FacetFilter from "sap/m/FacetFilter";
import type ComboBox from "sap/m/ComboBox";
import type CheckBox from "sap/m/CheckBox";
import type DatePicker from "sap/m/DatePicker";
import type DateTimePicker from "sap/m/DateTimePicker";
import type Input from "sap/m/Input";
import type InputBase from "sap/m/InputBase";
import type Select from "sap/m/Select";
import type Slider from "sap/m/Slider";
import type TimePicker from "sap/m/TimePicker";
import type SmartComboBox from "sap/ui/comp/smartfield/ComboBox";
import type SmartField from "sap/ui/comp/smartfield/SmartField";
import type SmartForm from "sap/ui/comp/smartform/SmartForm";
import type Form from "sap/ui/layout/form/Form";
import type FormElement from "sap/ui/layout/form/FormElement";
import type SimpleForm from "sap/ui/layout/form/SimpleForm";
import type MultiInput from "sap/m/MultiInput";
import type MultiComboBox from "sap/m/MultiComboBox";
import type ValueHelpDialog from "sap/ui/comp/valuehelpdialog/ValueHelpDialog";
import type Button from "sap/m/Button";
import type MessagePopover from "sap/m/MessagePopover";
import type ListBase from "sap/m/ListBase";
import type ListItemBase from "sap/m/ListItemBase";
import type TreeItemBase from "sap/m/TreeItemBase";
import type List from "sap/m/List";
import type Dialog from "sap/m/Dialog";
import type GroupHeaderListItem from "sap/m/GroupHeaderListItem";
import type FlexBox from "sap/m/FlexBox";
import type HBox from "sap/m/HBox";
import type VBox from "sap/m/VBox";
import type Toolbar from "sap/m/Toolbar";
import type OverflowToolbar from "sap/m/OverflowToolbar";
import type Title from "sap/m/Title";
import type { IResourceBundleAwareUIComponent } from "dbme/c/types/IComponent";
import type Controller from "sap/ui/core/mvc/Controller";
import type AppComponent from "sap/fe/core/AppComponent";
import type UIComponent from "sap/ui/core/UIComponent";
import type ComponentContainer from "sap/ui/core/ComponentContainer";
import type XMLView from "sap/ui/core/mvc/XMLView";
import type ToolbarSpacer from "sap/m/ToolbarSpacer";
export declare function isUI5Element(obj: unknown): obj is UI5Element;
export declare function isAppComponent(obj: unknown): obj is AppComponent;
export declare function isUIComponent(obj: unknown): obj is UIComponent;
export declare function isComponentContainer(obj: unknown): obj is ComponentContainer;
export declare function isContentContainer(obj: unknown): obj is IContentContainer;
export declare function isItemsContainer(obj: unknown): obj is IItemsContainer;
export declare function isButton(obj: unknown): obj is Button;
export declare function isDialog(obj: unknown): obj is Dialog;
export declare function isListBase(obj: unknown): obj is ListBase;
export declare function isListItemBase(c: object): c is ListItemBase;
export declare function isTreeItemBase(c: object): c is TreeItemBase;
export declare function isList(obj: unknown): obj is List;
export declare function isMessagePopover(obj: unknown): obj is MessagePopover;
export declare function isTable(obj: unknown): obj is Table;
export declare function isResponsiveTable(obj: unknown): obj is ResponsiveTable;
export declare function isSmartTable(obj: unknown): obj is SmartTable;
export declare function isFacetFilter(obj: unknown): obj is FacetFilter;
export declare function isInputBase(obj: unknown): obj is InputBase;
export declare function isInput(obj: unknown): obj is Input;
export declare function isMultiInput(obj: unknown): obj is MultiInput;
export declare function isSlider(obj: unknown): obj is Slider;
export declare function isComboBox(obj: unknown): obj is ComboBox;
export declare function isCheckBox(obj: unknown): obj is CheckBox;
export declare function isMultiComboBox(obj: unknown): obj is MultiComboBox;
export declare function isSelect(obj: unknown): obj is Select;
export declare function isSmartComboBox(obj: unknown): obj is SmartComboBox;
export declare function isSmartField(obj: unknown): obj is SmartField;
export declare function isSmartForm(obj: unknown): obj is SmartForm;
export declare function isSmartFilterBar(obj: unknown): obj is SmartFilterBar;
export declare function isForm(obj: unknown): obj is Form;
export declare function isFormElement(obj: unknown): obj is FormElement;
export declare function isSimpleForm(obj: unknown): obj is SimpleForm;
export declare function isDatePicker(obj: unknown): obj is DatePicker;
export declare function isDateTimePicker(obj: unknown): obj is DateTimePicker;
export declare function isTimePicker(obj: unknown): obj is TimePicker;
export declare function isValueHelpDialog(obj: unknown): obj is ValueHelpDialog;
export declare function isGroupHeaderListItem(obj: unknown): obj is GroupHeaderListItem;
export declare function isFlexBox(obj: unknown): obj is FlexBox;
export declare function isHBox(obj: unknown): obj is HBox;
export declare function isVBox(obj: unknown): obj is VBox;
export declare function isToolbar(obj: unknown): obj is Toolbar;
export declare function isOverflowToolbar(obj: unknown): obj is OverflowToolbar;
export declare function isTitle(obj: unknown): obj is Title;
export declare function isResourceBundleAwareUIComponent(component: unknown): component is IResourceBundleAwareUIComponent;
export declare function isController(obj: unknown): obj is Controller;
export declare function isXMLView(obj: unknown): obj is XMLView;
export declare function isToolbarSpacer(obj: unknown): obj is ToolbarSpacer;
